### ISSUE TITLE
Is this a requests modifier and/or https enforcer?

### ISSUE THREAD

**Issue by EC-O-DE** [evecalm/MyWebrequest#2]
Is this a requests modifier and/or https enforcer? I'm on Opera, and it lacks serious good https enforcer. That would also be compatible with Opera's built in VPN. This extension looks good because it would be good if one could do more regarding requests than just https enforcing (and dropping to http is SSL not found).

Interesting stuff you have going on here. And there's only a handful (so it seems) who have installed this at Chrome store.

I see files here on Github are a lot newer. Is this later development stable(ish)?

**Comment by oe** [comment]
Yes, this extension is mainly based on API of [chrome.webRequest](https://developer.chrome.com/extensions/webRequest).

If you want to enforce https and downgrade to http if no ssl available, you could try extension [https-everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en). 

There have no stable version on dev branch, it's still in developing, and will come with some new features. I'm too busy to continue this project. I will continue it when I catch some time.
