### ISSUE TITLE
请教自定义跳转的问题

### ISSUE THREAD

**Issue by miaomiaosoft** [evecalm/MyWebrequest#4]
你好！
例如，将 
http://store.akamai.steamstatic.com/public/shared/images/responsive/header_logo.png
跳转至
https://steamcommunity-a.akamaihd.net/public/shared/images/responsive/header_logo.png

我尝试过例如
http://store.akamai.steamstatic.com/{*rest}
https://steamcommunity-a.akamaihd.net/{rest}
和一些其他的组合发现都无法测试匹配成功，可否麻烦提供一个正确的规则示例，感谢！

**Comment by oe** [comment]
可以尝试使用 `https://steamcommunity-a.akamaihd.net/{r}` 

MyWebrequest 正在缓慢重构中, 自定义跳转URL的功能会更完善的

**Comment by miaomiaosoft** [comment]
好的，感谢！
