### ISSUE TITLE
360极速浏览器划词搜索功能url重定向失败

### ISSUE THREAD

**Issue by tianqing617** [evecalm/MyWebrequest#6]
360极速浏览器划词搜索功能不法重定向到谷歌，还是打开so.com进行搜索。测试百度、bing都可以。
配置如下：
*://www.so.com/s?q={kwd}
https://www.google.com/search?q={kwd}

**Comment by oe** [comment]
问题已经在dev分支修复,  因为dev功能还未开发完, 所以暂未发布, 再耐心等候一个月吧, 到时候还会有其他`重磅` 功能发布

**Comment by tianqing617** [comment]
@evecalm 新版本还没有发布吗？

**Comment by oe** [comment]
@lhard66 这段时间有些忙, 得再拖一拖了
